/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every frame the server sends over `/ws`.
         *
         *     This is exported into the OpenAPI document so the generated TypeScript
         *     client carries the socket contract too. The REST half already has a CI
         *     drift gate; without this the `"RESYNC"` tag the client switches on was
         *     matched to the server by hand.
         */
        ClientFrame: {
            /** Format: uuid */
            boot_id: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "HELLO";
        } | {
            envelope: components["schemas"]["Envelope"];
            /** @enum {string} */
            type: "EVENT";
        } | {
            /** @enum {string} */
            type: "RESYNC";
        };
        /**
         * @description One published event, as it appears on the wire.
         *
         *     `boot_id` changes on every server start and `seq` increases by exactly
         *     one per event, so a client can detect both a restart and a gap and
         *     respond with the same action: refetch.
         */
        Envelope: {
            /** Format: date-time */
            at: string;
            /** Format: uuid */
            boot_id: string;
            /**
             * @description One of the `EventKind` variants, SCREAMING_SNAKE_CASE (e.g. `PING`).
             * @example PING
             */
            kind: string;
            payload: unknown;
            /** Format: int64 */
            seq: number;
            /**
             * @description The topic key: `staff`, or `station:<uuid>` / `table:<uuid>` /
             *     `check:<uuid>`.
             * @example staff
             */
            topic: string;
        };
        HealthResponse: {
            /** @description Always "ok" when the process is serving requests. */
            status: string;
            /**
             * Format: int64
             * @description Seconds since the process started.
             */
            uptime_seconds: number;
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is serving requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
